[project]
name = "mlops-labolatories"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sonia", email = "sweiss@student.agh.edu.pl" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "joblib>=1.6.0",
    "pre-commit>=4.6.2",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
mlops-labolatories = "mlops_labolatories:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-dotenv>=0.5.2",
    "types-pyyaml>=6.0.12.20260906",
]

[tool.pytest.ini_options]
pythonpath = ["."]
env_files = ["./config/.env.test"]

[tool.mypy]
ignore_missing_imports = true
